language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.5'
  - '3.6'
  - 3.7-dev
  - pypy
  - pypy3
install:
  - pip install -r requirements.txt
script:
  - python setup.py build install
  - python -m coverage run --source=xtea setup.py test
  - python -m coverage report --fail-under 80
after_script:
  - python -m coverage xml
  - bash <(curl -s https://codecov.io/bash)
