name: bdist_wheel

on: [push]

jobs:
  bdist_wheel:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15, windows-2019]
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: bdist_wheel
      run: |
        python setup.py bdist_wheel --py-limited-api cp35
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: dist/*.whl
