name: Build Packages

on: [push]

jobs:
  bdist_wheel:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15, windows-2019]
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build sdist
      shell: pwsh
      run: |
        if ($PSVersionTable.Platform -ne "Unix") {
          python setup.py sdist --formats zip,gztar,xztar,bztar
        }
    - name: Build fallback wheel
      shell: pwsh
      run: |
        if ($PSVersionTable.Platform -ne "Unix") {
          python setup.py bdist_wheel --exclude-extension
        }
    - name: Build abi3 wheel
      run: |
        python setup.py bdist_wheel --py-limited-api cp35
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: dist/*

  manylinux1:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build abi3 wheel
      run: |
        for P in manylinux1_x86_64 manylinux1_i686; do
          if [ "$P" = manylinux1_i686 ]; then
            PRE="linux32"
          else
            PRE=""
          fi
          docker pull quay.io/pypa/$P
          docker run --rm -e PLAT=$P -v $(pwd):/io quay.io/pypa/$P $PRE sh -c "
            cd /io
            /opt/python/cp36-cp36m/bin/pip install -r requirements.txt
            /opt/python/cp36-cp36m/bin/python3 setup.py bdist_wheel --py-limited-api cp35
            auditwheel repair dist/*.whl
          "
        done
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl